# requirements.yml

# This file is used to define the Ansible roles that are required for your playbooks.
# You can specify the name and version of each role you want to include in your project.

roles:
  - name: geerlingguy.postgresql
    version: 4.1.0
  - name: geerlingguy.apache
    version: 4.2.1
    src: git+https://github.com/geerlingguy/ansible-role-apache
    # see https://github.com/geerlingguy/ansible-role-apache for tags
  - name: geerlingguy.php
    version: 6.1.0
    src: git+https://github.com/geerlingguy/ansible-role-php
